PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX htrc: <http://wcsa.htrc.illinois.edu/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ht: <https://www.hathitrust.org/>
PREFIX prism: <http://prismstandard.org/namespaces/basic/2.0/>
PREFIX astrs: <http://www.w3.org/ns/activitystreams#>
PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
PREFIX madsrdf: <http://www.loc.gov/mads/rdf/v1#>
prefix schema: <http://schema.org/>

CONSTRUCT {
	?item	schema:publisher	?publisher . 

	?publisher	a	<http://id.loc.gov/ontologies/bibframe/Organization> ;
				schema:name	?pubName .
}
WHERE {
		
	?item	dcterms:title	?title  .
	?item	bf:itemOf	?Inst .

	OPTIONAL {	?Inst		bf:provisionActivity/bf:agent	?publisher .
				?publisher 	rdfs:label	?pubName .
	}

	VALUES (?item) {
		( ?handle_url )
	}
}